KFSPTS-6675: Reduce the AFT code base to a single project and stop building the kuality-kfs Gem. This was done by merging the kuality-kfs-cu project into the kuality-kfs project and removing any code that built or define the gem.
CU-CommunityApps/kuality-kfs pull request #13
Opened 2016-10-20 15:09 UTC by nkimble

2016-10-20 19:08 UTC, bhutchinson requested changes
In general, changes look good to me. I noted some examples of what seemed like extra blank lines that could be removed and some places where kuality-kfs-cu seemed like it should be renamed to kuality-kfs.

2016-10-20 19:08 UTC, bhutchinson commented on README.md
> +1) Setup the kuality-kfs-cu GitHub project in your IDE as you would any other Ruby project.
This should probably be "kuality-kfs" now right?

2016-10-20 19:08 UTC, bhutchinson commented on README.md
> +..* **Working directory:** The kuality-kfs-cu project base directory
"kuality-kfs" here as well

2016-10-20 19:08 UTC, bhutchinson commented on features/step_definitions/financial_processing/auditing.rb
> +
this is really nitpicky, but seems like a lot of extra whitespace here

2016-10-20 19:08 UTC, bhutchinson commented on features/step_definitions/financial_processing/auxiliary_voucher.rb
> +
another place with extra blank lines - do we need all these blank lines? maybe I missed some other instances of this above?

2016-10-20 19:08 UTC, bhutchinson commented on features/step_definitions/financial_processing/disbursement_voucher.rb
> +
will one blank line do here instead of five?

2016-10-20 19:08 UTC, bhutchinson commented on features/step_definitions/financial_processing/labor_journal_voucher.rb
> +
one or two instead of three blank lines?

2016-10-20 19:08 UTC, bhutchinson commented on features/step_definitions/purap/requisition.rb
> +
blank lines here too

2016-10-20 19:08 UTC, bhutchinson commented on features/step_definitions/purap/requisition_base.rb
> +
fewer blank lines?

2016-10-20 19:08 UTC, bhutchinson commented on features/step_definitions/vendor/vendor.rb
> +
fewer blank lines?

2016-10-20 19:08 UTC, bhutchinson commented on lib/resources/cucumber_json_merge.rb
> +# cucumber_json_merge.rb -o ../kuality-kfs-cu-output.json ../kuality-kfs-cu-output.split*.json
probably not a big deal, but should "kuality-kfs-cu" be changed to "kualit-kfs" here?

2016-10-20 19:08 UTC, bhutchinson commented on lib/resources/cucumber_json_merge.rb
> +options[:output_file] = 'kuality-kfs-cu-output.json'
should this be changed to "kuality-kfs-output.json"?

2016-10-21 11:58 UTC, nkimble commented on README.md
> +1) Setup the kuality-kfs-cu GitHub project in your IDE as you would any other Ruby project.
Yes. Changing.

2016-10-21 11:59 UTC, nkimble commented on README.md
> +..* **Working directory:** The kuality-kfs-cu project base directory
Yes. Changing.

2016-10-21 12:10 UTC, nkimble commented on features/step_definitions/financial_processing/auditing.rb
> +
Removed lines.

2016-10-21 12:10 UTC, nkimble commented on features/step_definitions/financial_processing/auxiliary_voucher.rb
> +
Removed lines.

2016-10-21 12:11 UTC, nkimble commented on features/step_definitions/financial_processing/disbursement_voucher.rb
> +
Removed lines

2016-10-21 12:13 UTC, nkimble commented on features/step_definitions/purap/requisition.rb
> +
Removed lines

2016-10-21 12:14 UTC, nkimble commented on features/step_definitions/purap/requisition_base.rb
> +
Removed lines.

2016-10-21 12:15 UTC, nkimble commented on features/step_definitions/vendor/vendor.rb
> +
Removed lines

2016-10-21 12:34 UTC, nkimble commented on lib/resources/cucumber_json_merge.rb
> +# cucumber_json_merge.rb -o ../kuality-kfs-cu-output.json ../kuality-kfs-cu-output.split*.json
Changing to kuality-kfs as requested.  Doing so has implications to the Jenkins jobs that run on the server for the daily run.  Those server side  change will not be required for a while so creating another user story to track those future needed changes.

2016-10-21 12:34 UTC, nkimble commented on lib/resources/cucumber_json_merge.rb
> +options[:output_file] = 'kuality-kfs-cu-output.json'
Changing to kuality-kfs as requested. Doing so has implications to the Jenkins jobs that run on the server for the daily run. Those server side change will not be required for a while so creating another user story to track those future needed changes.

2016-10-21 12:52 UTC, nkimble commented
Requested changes have been made and code is ready to be reviewed again.

2016-10-21 12:57 UTC, bhutchinson approved these changes

2016-10-21 12:58 UTC, bhutchinson commented
Changes look good, merging.

2016-10-21 13:00 UTC, merged